### ISSUE TITLE
pkhex always maxes out pp

### ISSUE THREAD

**Issue by DerpyScape** [santacrab2/PKHeXMAUI#11]
I've observed that every time I edit a pokemon, all of its moves are suddenly maxed out of pp without me even editing it and I can't edit it out. Is it perhaps a bug or designed the way it is

**Comment by santacrab2** [comment]
If you are importing by showdown set ALM is designed that way. I was able to edit them out just fine though. I'll change the behavior on next update though to update the change to pps live instead of requiring a pull down to refresh to update.
