### ISSUE TITLE
Livehex Error

### ISSUE THREAD

**Issue by Zeyzers** [santacrab2/PKHeXMAUI#12]
When trying to connect to my switch through Livehex it says "Error invalid version detected. could not connect to device".
IP is correct and the port too.
with livehex on pc it works fine.

**Comment by santacrab2** [comment]
What game are you getting this error on? I couldn't replicate on SV.

**Comment by Zeyzers** [comment]
Im using Pokemon Legends: Arceus

**Comment by santacrab2** [comment]
I was able to replicate by having the wrong blank save file opened. Make sure you switch to a blank Legends: Arceus save file before connecting. You can do this by going to Settings and using the drop down to change to Legends: Arceus prior to connecting.
