### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by Tomomoto10** [santacrab2/PKHeXMAUI#14]
ive just noticed that the update has an issue with the apk info. 
Im on GraphineOs using Obtainium to update driect from your Github. It says latest version is 24.12.11 but after installing update it stays at 1.0 and wants to update again. I direct downloaded from browser and have the same issue. 
Ive opned the apk in APKTool M and can see it is still 1.0 on the version release. Ive had this issue before and is easy fixed by changing the release version and version code in quick edit then re installing.

**Comment by santacrab2** [comment]
versioning isn't done through the APK version, it is done internally through my own system. This may or may not be compatible with third party tools.

**Comment by Tomomoto10** [comment]
Oh i get you, stange though becuase it definitely works after changing apk version in APKtool M. This happened with a few github repositories though not just yours, all have that same fix..
