### ISSUE TITLE
Hey Mr krabs

### ISSUE THREAD

**Issue by hexbyt3** [santacrab2/PKHeXMAUI#6]
Hello, upon joining your server I was insta banned and I don’t know why. I’m a friendly Gengar :(

**Comment by santacrab2** [comment]
Are you the one with a literal website as your username? If so I think you can figure out why you were instabanned.

**Comment by hexbyt3** [comment]
I’m sorry, it’s a website similar to showdown to help people gen but more like pkhex online. I also have an online seed finder on there too. It’s not a bad website lol. You should check it out. It’s almost as cool as some of the stuff you’ve built for the community. I also made a pretty rad raid bot :)

https://genpkm.com

**Comment by hexbyt3** [comment]
I’m a developer too and was hoping to link up sometime :)

**Comment by santacrab2** [comment]
unbanned

**Comment by hexbyt3** [comment]
Thanks Santa <3
