### ISSUE TITLE
egg

### ISSUE THREAD

**Issue by ZiYuKing** [santacrab2/PKHeXMAUI#8]
If the language of an egg is modified, it is illegal. Trash need to be added.

**Comment by santacrab2** [comment]
If you double tap on where it says Nickname it will open the trash editor. Same with double tapping on where it says OT.
This is the same behavior as PC PKHeX, changing the language of an egg there will also lead to an illegal mon.
<br><br>![image](https://github.com/user-attachments/assets/6b611def-7c47-4d33-9d4b-df9cd6659696)
