### ISSUE TITLE
pkhex maui crash when i chose the target game

### ISSUE THREAD

**Issue by luizao-rizz** [santacrab2/PKHeXMAUI#9]
i want to legalize a quagsire but when i chose the target game (in the case of pokemon heart gold) the app restarts and don't choose the game i want

**Comment by santacrab2** [comment]
I am a little confused on what exactly the steps are to produce this issue. Can you go further into the exact steps you are taking to produce this error? Can you clarify what you mean by target game e.g. Met Location versus the game it currently resides in.

**Comment by luizao-rizz** [comment]
i literally go to the options and choose the target game and the app restarts and the target game is blank

**Comment by santacrab2** [comment]
I see. I can replicate and will investigate. Thanks for the report!

**Comment by santacrab2** [comment]
Just a quick update on this matter. This has been discovered to be purely a visual bug. The blank save file it switches to is still a HGSS blank save. I am working on fixing this visual bug, but in the meantime this should not impact the functionality of the app.

**Comment by santacrab2** [comment]
fixed with #6a0d95b

**Comment by luizao-rizz** [comment]
ok thanks

Em sex., 6 de set. de 2024 11:44 AM, santacrab2 ***@***.***>
escreveu:
